// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace DesignPatternPractice
{
	public class WarriorCraetor: Creator
	{
		public WarriorCraetor ()
		{
			Console.WriteLine("Create WarriorCreator!");
		}

		public Unit Create(string unitName)
		{
			unitName = unitName.ToLower();

			switch( unitName )
			{
			case "warrior":
				return new Warrior( unitName );
			case "knight":
				return new Knight( unitName );
			default:
				return null;
			}
		}
	}
}

